"""
Sorting hat questions
"""

questions = [
    
    "You are given a team project to complete\n"
    "in school. What role do you play in the team?\n"
    "(a) The organiser, assigning roles and tasks"
    "to others in the team"
    "(b) Team projects are great, I can let everyone"
    "else do all the work!"
    "(c) I work hard to make sure I am a good member"
    "of the team."
    "(d) I work away on my own, researching the best"
    "options."

    "Its sports day and you are competing in a number\n"
    "of events. Do you.."
    "(a) Put in lots of practice in the weeks before"
    "You want to win!"
    "(b) Do whatever it takes to win..if that means"
    "tripping someone esle up so be it!"
    "(c) Give it my best effort but at the end of the"
    "day the best boy or girl wins!"
    "(d) Sports day? Uggh can we not do soemthing more"
    "interesting?!."

    "You see another pupil being teased about their clothes."
    "Do you.."
    "(a) Threaten the bullies and tell them to back off."
    "(b) Laugh and maybe join in."
    "(c) Find the pupil afterwards and talk to them."
    "(d) Feel sorry for them but mind your own business."

    "Which profession appeals to you the most.."
    "(a) "
    "(b) "
    "(c) "
    "(d) "  

    "You went to HoneyDukes to buy some sweets but"
    "realised later you were undercharged. Do you.."
    "(a) Go straight back to tell them and pay the "
    "correct amount"
    "(b) Think brilliant! Their mistake is my win!"
    "(c) Remember to go back next time you are in"
    "Diagon Alley and pay the difference"
    "(d) Think oh that's lucky!"   

    "What is your ideal position in a game of Quidditch?"
    "(a) Seeker"
    "(b) Beater"
    "(c) Chaser"
    "(d) Team supporter - I am happy in the stands thanks"  

    "Someone is calling you names. Which do you find most"
    "upsetting?"
    "(a) Weak"
    "(b) Boring"
    "(c) Cheater"
    "(d) Stupid" 

    "You value friends that are..."
    "(a) Brave and adventurous"
    "(b) Popular and admired"
    "(c) Kind and loyal"
    "(d) Intelligent" 

    "You are most likely to get in trouble for..."
    "(a) Punching a bully"
    "(b) Cheating on an exam"
    "(c) I don't get in trouble!"
    "(d) Staying up late reading" 

    "Placeholder."
    "(a) "
    "(b) "
    "(c) "
    "(d) " 
]